### ISSUE TITLE
You Should Complie your Project

### ISSUE THREAD

**Issue by solka2050** [marcoschwartz/arduino-wifi-powerswitch#1]
This report would have more information with
  "Show verbose output during compilation"
  enabled in File > Preferences.
Arduino: 1.0.6 (Windows NT (unknown)), Board: "Arduino Uno"
Binary sketch size: 32,342 bytes (of a 32,256 byte maximum)

processing.app.debug.RunnerException: Sketch too big; see http://www.arduino.cc/en/Guide/Troubleshooting#size for tips on reducing it.

```
at processing.app.Sketch.size(Sketch.java:1653)

at processing.app.Sketch.build(Sketch.java:1586)

at processing.app.Sketch.build(Sketch.java:1562)

at processing.app.Editor$DefaultRunHandler.run(Editor.java:1899)

at java.lang.Thread.run(Thread.java:619)
```

**Comment by marcoschwartz** [comment]
Hello, 

I just saw you also posted on the aREST library repository. The answer is simple: you should use Arduino 1.6 :) I'll let you download it on the Arduino main page. Let me know if it works, I'll close the other issue and leave this one open.
