### ISSUE TITLE
TypeError: arest.send is not a function

### ISSUE THREAD

**Issue by mattkimdesign** [marcoschwartz/arduino-wifi-powerswitch#2]
Hello,

I am following your wifi power switch tutorial and succeed until the very last part, the Interface. I installed the aRest module through the terminal. Once I installed node app.js and open my browser and saw on/off button with offline. Waited more than 10 minutes. I did not see the green"Device online" text. I checked my terminal and saw this " TypeError: arest.send is not a function"
Is that would be the problem? Please teach me how to resolve this issue ASAP

below is the copy of terminal:

matts-MacBook-Pro-2:interface dkim49$ node app.js
Listening on port 3700
express deprecated res.sendfile: Use res.sendFile instead app.js:16:7
TypeError: arest.send is not a function
    at /Users/dkim49/Desktop/Arduino/arduino-wifi-powerswitch-master/interface/app.js:21:9
    at Layer.handle [as handle_request](/Users/dkim49/Desktop/Arduino/arduino-wifi-powerswitch-master/interface/node_modules/express/lib/router/layer.js:95:5)
    at next (/Users/dkim49/Desktop/Arduino/arduino-wifi-powerswitch-master/interface/node_modules/express/lib/router/route.js:131:13)
    at Route.dispatch (/Users/dkim49/Desktop/Arduino/arduino-wifi-powerswitch-master/interface/node_modules/express/lib/router/route.js:112:3)
    at Layer.handle [as handle_request](/Users/dkim49/Desktop/Arduino/arduino-wifi-powerswitch-master/interface/node_modules/express/lib/router/layer.js:95:5)
    at /Users/dkim49/Desktop/Arduino/arduino-wifi-powerswitch-master/interface/node_modules/express/lib/router/index.js:277:22
    at Function.process_params (/Users/dkim49/Desktop/Arduino/arduino-wifi-powerswitch-master/interface/node_modules/express/lib/router/index.js:330:12)
    at next (/Users/dkim49/Desktop/Arduino/arduino-wifi-powerswitch-master/interface/node_modules/express/lib/router/index.js:271:10)
    at SendStream.error (/Users/dkim49/Desktop/Arduino/arduino-wifi-powerswitch-master/interface/node_modules/express/node_modules/serve-static/index.js:120:7)
    at emitOne (events.js:77:13)

**Comment by marcoschwartz** [comment]
Hello,

Indeed I just checked, this tutorial is using an old version of the aREST node.js module. I'll make sure to update it soon.

**Comment by marcoschwartz** [comment]
Hello, I checked the article, it seems that the code for this article was moved to: https://github.com/openhomeautomation/arduino-wifi-switch Let me know if that works!
